# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: myRise Documentation
    url: [Your documentation URL when available]
    about: Check the documentation before creating an issue

# You can add more contact links as needed

# The templates will be listed in the order they appear in the directory