"""projects table add updated and etag for commits from path

Revision ID: 5e52a1295d4d
Revises: f7ae36415c32
Create Date: 2025-03-25 08:03:15.053946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e52a1295d4d'
down_revision = 'f7ae36415c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('path_etag', sa.String(length=250), nullable=True))
        batch_op.drop_column('complete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete', sa.DATE(), nullable=True))
        batch_op.drop_column('path_etag')
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
