"""add path commits field to project table

Revision ID: 847622cd1f4e
Revises: 5e52a1295d4d
Create Date: 2025-03-25 08:50:44.921926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847622cd1f4e'
down_revision = '5e52a1295d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path_commits', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('path_commits')

    # ### end Alembic commands ###
