"""add relationship from repo to events

Revision ID: f1a71d72c7ff
Revises: cbad485d4805
Create Date: 2024-10-22 15:31:44.315419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a71d72c7ff'
down_revision = 'cbad485d4805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repo_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_events_repo_id'), ['repo_id'], unique=False)
        batch_op.create_foreign_key(None, 'repos', ['repo_id'], ['id'])
        batch_op.drop_column('repo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repo', sa.VARCHAR(length=250), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_events_repo_id'))
        batch_op.drop_column('repo_id')

    # ### end Alembic commands ###
